Add  docker cleanup

diff --git a/.github/workflows/aws-ecr.yml b/.github/workflows/aws-ecr.yml
--- a/.github/workflows/aws-ecr.yml
+++ b/.github/workflows/aws-ecr.yml
@@ -37,6 +37,21 @@ jobs:
     - name: Login to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v2
+
+    - name: Free up Disk Space
+      run: |
+            # Remove specific Docker images that are no longer needed
+            docker rmi $(docker images -f "dangling=true" -q) || true
+            
+            # Prune unused Docker objects (images, containers, volumes, and networks)
+            docker system prune -f || true
+
+            # Clean up specific directories known to consume a lot of space
+            #sudo rm -rf /path/to/large/directory
+
+            # Show disk space usage
+            df -h
+
       
     - name: Build Docker image
       run: |
